"""initial schema

Revision ID: 2b5868bd9e49
Revises: 
Create Date: 2025-08-26 18:17:50.774346

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2b5868bd9e49'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('offender',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('roll_number', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('image_path', sa.String(length=400), nullable=True),
    sa.Column('face_encoding', sa.PickleType(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('roll_number')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=True),
    sa.Column('name', sa.String(length=120), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('face_encoding', sa.PickleType(), nullable=True),
    sa.Column('phone', sa.String(length=30), nullable=True),
    sa.Column('student_id', sa.String(length=50), nullable=True),
    sa.Column('otp', sa.String(length=8), nullable=True),
    sa.Column('otp_verified', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('penalties',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('offender_id', sa.Integer(), nullable=True),
    sa.Column('offender_name', sa.String(length=120), nullable=True),
    sa.Column('offender_email', sa.String(length=120), nullable=True),
    sa.Column('image_path', sa.String(length=400), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.Column('matched', sa.Boolean(), nullable=True),
    sa.Column('paid', sa.Boolean(), nullable=True),
    sa.Column('amount', sa.Float(), nullable=True),
    sa.Column('token', sa.String(length=100), nullable=True),
    sa.Column('token_expiry', sa.DateTime(), nullable=True),
    sa.Column('otp', sa.String(length=8), nullable=True),
    sa.Column('otp_verified', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['offender_id'], ['offender.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('token')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('penalties')
    op.drop_table('users')
    op.drop_table('offender')
    # ### end Alembic commands ###
