"""Add department/year/photo_filename to Offender + useful indexes

Revision ID: d8d9849adbe2
Revises: 2b5868bd9e49
Create Date: 2025-08-26 20:35:07.575852

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd8d9849adbe2'
down_revision = '2b5868bd9e49'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offender', schema=None) as batch_op:
        batch_op.add_column(sa.Column('department', sa.String(length=80), nullable=True))
        batch_op.add_column(sa.Column('year', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('photo_filename', sa.String(length=200), nullable=True))
        batch_op.create_index(batch_op.f('ix_offender_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_offender_roll_number'), ['roll_number'], unique=True)

    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_penalties_matched'), ['matched'], unique=False)
        batch_op.create_index(batch_op.f('ix_penalties_paid'), ['paid'], unique=False)
        batch_op.create_index(batch_op.f('ix_penalties_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_penalties_token'), ['token'], unique=True)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_email'))

    with op.batch_alter_table('penalties', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_penalties_token'))
        batch_op.drop_index(batch_op.f('ix_penalties_timestamp'))
        batch_op.drop_index(batch_op.f('ix_penalties_paid'))
        batch_op.drop_index(batch_op.f('ix_penalties_matched'))

    with op.batch_alter_table('offender', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offender_roll_number'))
        batch_op.drop_index(batch_op.f('ix_offender_email'))
        batch_op.drop_column('photo_filename')
        batch_op.drop_column('year')
        batch_op.drop_column('department')

    # ### end Alembic commands ###
